CAAPIM/Android-MAS-SDK

- MAS/MASTest/src/androidTest/java/com/ca/mas/sample/testapp/suite/InstrumentationTestSuite.java
- MAS/MASTest/src/androidTest/java/com/ca/mas/sample/testapp/tests/instrumentation/base/MASIntegrationBaseTest.java
- MAS/MASTest/src/androidTest/java/com/ca/mas/sample/testapp/tests/instrumentation/connecta/MASConnectaPublicBrokerTests.java
- MAS/MASTest/src/androidTest/java/com/ca/mas/sample/testapp/tests/instrumentation/connecta/MASConnectaTests.java
- MAS/src/main/java/com/ca/mas/connecta/client/ConnectOptions.java
- MAS/src/main/java/com/ca/mas/connecta/client/MASConnectOptions.java
- MAS/src/main/java/com/ca/mas/connecta/client/MASConnectaClient.java
- MAS/src/main/java/com/ca/mas/connecta/client/MASConnectaManager.java
- MAS/src/main/java/com/ca/mas/connecta/serviceprovider/ConnectaService.java
- MAS/src/main/java/com/ca/mas/connecta/util/ConnectaConsts.java
- MAS/src/main/java/com/ca/mas/connecta/util/ConnectaUtil.java
- MAS/src/main/java/com/ca/mas/foundation/util/FoundationUtil.java
- MAS/src/main/java/com/ca/mas/messaging/MASMessage.java
Implementation for aligning pub/sub with iOS.
Rally story: https://rally1.rallydev.com/#/56296942493d/detail/userstory/65886723888
> Us240431 align pub sub

- MASUI/src/main/java/com/ca/mas/ui/otp/MASOtpDialogFragment.java
https://rally1.rallydev.com/#/56296942493ud/detail/defect/71674074948
> [DE243884] Null check for OTP dialog check boxes

- MAS/src/main/java/com/ca/mas/identity/user/UserIdentityManager.java
https://rally1.rallydev.com/#/56296942493ud/detail/userstory/65883336848
> [US240423] Preliminary fingerprint UI implementation

- MAS/src/main/java/com/ca/mas/connecta/serviceprovider/ConnectaService.java
Take MASMessage parameters into account when creating MqttMessage.
> [US240431] - Take MASMessage parameters into account 

- MAS/src/main/java/com/ca/mas/foundation/MASFoundationStrings.java
- MAS/src/main/java/com/ca/mas/foundation/MASUser.java
- MAS/src/main/java/com/ca/mas/storage/MASSecureLocalStorage.java
Can now invoke even with an expired token, local storage is now blocked with a locked session
> [DE245856] Take 3

- MAS/src/main/java/com/ca/mas/foundation/MASUser.java
As discussed in point 1 of your email. Should be the last 'bug' of this story.
> [DE245856] Rejecting logout if the session is locked

- MAG/MAGTest/src/androidTest/java/com/ca/mas/core/test/DefaultDispatcher.java
- MAG/MAGTest/src/androidTest/java/com/ca/mas/core/test/error/MAGEndpointTest.java
- MAG/MAGTest/src/androidTest/java/com/ca/mas/core/test/error/OAuthEndpointTest.java
- MAG/src/main/java/com/ca/mas/core/client/ServerClient.java
- MAG/src/main/java/com/ca/mas/core/context/MssoContext.java
- MAG/src/main/java/com/ca/mas/core/oauth/OAuthTokenClient.java
- MAG/src/main/java/com/ca/mas/core/policy/AccessTokenAssertion.java
- MAG/src/main/java/com/ca/mas/core/policy/ClientCredentialAssertion.java
- MAG/src/main/java/com/ca/mas/core/policy/DeviceRegistrationAssertion.java
- MAG/src/main/java/com/ca/mas/core/policy/PolicyManager.java
- MAG/src/main/java/com/ca/mas/core/policy/exceptions/CertificateExpiredException.java
- MAG/src/main/java/com/ca/mas/core/policy/exceptions/InvalidClientCredentialException.java
- MAG/src/main/java/com/ca/mas/core/policy/exceptions/RetryRequestException.java
- MAG/src/main/java/com/ca/mas/core/registration/RegistrationClient.java
- MAG/src/main/java/com/ca/mas/core/service/MssoService.java
- MAS/src/main/java/com/ca/mas/foundation/MASConfiguration.java
New handling of renew device.
Updated test cases.
MASConfiguration supports setting days to expire.
> Us240491 client cert life manage

- MASUI/src/main/java/com/ca/mas/ui/MASEnterpriseBrowserFragment.java
https://rally1.rallydev.com/#/56296942493ud/detail/defect/74109851000
> [DE248776] MASEnterpriseBrowserFragment application launcher changes

- MAG/src/main/java/com/ca/mas/core/conf/ConfigurationManager.java
- MAG/src/main/java/com/ca/mas/core/policy/DeviceRegistrationAssertion.java
- MAS/src/main/java/com/ca/mas/foundation/MASConfiguration.java
Renamed ‘days to expire’ variable to align with iOS.
> [US240491] - Renamed ‘days to expire’ variable.

- MAS/src/main/java/com/ca/mas/connecta/util/ConnectaConsts.java
- MAS/src/main/java/com/ca/mas/messaging/MASMessage.java
> [DE254536]

- mas/mastest/src/androidTest/java/com/ca/mas/sample/testapp/tests/instrumentation/connecta/MASConnectaPublicBrokerTests.java
- mas/src/main/java/com/ca/mas/connecta/serviceprovider/ConnectaService.java
- mas/src/main/java/com/ca/mas/connecta/util/ConnectaUtil.java
Changed MqqtClient to MqttAsyncClient.
Removed mag identifier from mqtt client ID for public broker.
Changed broker for public broker unit tests.
> De255170 messaging not on ui thread

- mag/build.gradle
Remove scprov from mag/build.gradle
> remove reference to spongy castle, don't import scprov-jdk15on

- mag/magtest/src/androidTest/java/com/ca/mas/core/test/RenewDeviceTest.java
- mag/src/main/java/com/ca/mas/core/MobileSso.java
- mag/src/main/java/com/ca/mas/core/MobileSsoFactory.java
- mag/src/main/java/com/ca/mas/core/context/MssoContext.java
- mag/src/main/java/com/ca/mas/core/creds/AuthorizationCodeCredentials.java
- mag/src/main/java/com/ca/mas/core/creds/ClientCredentials.java
- mag/src/main/java/com/ca/mas/core/creds/JWTCredentials.java
- mag/src/main/java/com/ca/mas/core/http/MAGRequest.java
- mag/src/main/java/com/ca/mas/core/request/internal/MAGRequestProxy.java
- mag/src/main/java/com/ca/mas/core/service/MssoClient.java
- mas/mastest/src/androidTest/java/com/ca/mas/sample/testapp/tests/instrumentation/base/MASIntegrationBaseTest.java
- mas/src/androidTest/java/com/ca/mas/MASTokenRequest.java
- mas/src/androidTest/java/com/ca/mas/foundation/MASLoginTest.java
- mas/src/androidTest/java/com/ca/mas/foundation/MASTest.java
- mas/src/main/java/com/ca/mas/foundation/MASIdToken.java
- mas/src/main/java/com/ca/mas/foundation/MASRequest.java
- mas/src/main/java/com/ca/mas/foundation/MASUser.java
* Login with ID TOKEN implementation
* Access non-protected endpoint on the gateway.
> [US308531]

- CONTRIBUTING.md
- GUIDELINES.md
- README.md
> Us408699 android product name changes

- CONTRIBUTING.md
- GUIDELINES.md
- README.md
> Android sdk product names

- ChangeLog.md
Put info where developers can act on it.
> Added Android content from RN

- ChangeLog.md
- mas-foundation/src/main/java/com/ca/mas/core/auth/AuthRenderer.java
- mas-foundation/src/main/java/com/ca/mas/core/auth/PollingRenderer.java
- mas-foundation/src/main/java/com/ca/mas/core/auth/ble/BluetoothLeCentralRenderer.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MASUser.java
- masui/src/main/java/com/ca/mas/ui/MASLoginActivity.java
> DE345468: Login via QR code with multi user support false

- ChangeLog.md
- mas-foundation/src/main/java/com/ca/mas/foundation/auth/MASApplication.java
> Notify on cancel

- README.md
Added trademark and aligned to other repos
> Us494007 landing repo g aedits

- mas-foundation/src/androidTest/java/com/ca/mas/core/storage/AccountManagerStorageTests.java
- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASSecureSharedStorageTest.java
- mas-foundation/src/androidTest/java/com/ca/mas/foundation/PerformanceComparisonStorageTest.java
US240348 - Implement SecureAccountManager
- Added some test for mesure the performance (time) between old AccountManager and new MASSecureSharedStorage
> US240348 - Implement SecureAccountManager Performance Test

- mas-foundation/build.gradle
DE369928-API-reference-docs
-- Generate everything but the excluded ones
[mas_foundation_javadoc.zip](https://github.com/CAAPIM/Android-MAS-SDK/files/2206713/mas_foundation_javadoc.zip)
> DE369928-API-reference-docs

- ChangeLog.md
- mas-foundation/src/main/java/com/ca/mas/foundation/MASFoundationStrings.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MASUser.java
DE377125 - lockSession message
- Check if the device has Screen lock if not throw error Screen lock is not active
> DE377125 - lockSession message

- ChangeLog.md
- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASJwtSigningTest.java
- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASLoginTest.java
- mas-foundation/src/main/java/com/ca/mas/core/conf/ConfigurationManager.java
- mas-foundation/src/main/java/com/ca/mas/core/token/JWTValidation.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MAS.java
TA1131131-Configurable-IDTokenValidation
- IDtoken Validation
> TA1131131-Configurable-IDTokenValidation

- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASSecureSharedStorageTest.java
> fix test case for API19

- ChangeLog.md
- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASDeviceTest.java
- mas-foundation/src/main/java/com/ca/mas/core/MobileSsoConfig.java
- mas-foundation/src/main/java/com/ca/mas/core/conf/Config.java
- mas-foundation/src/main/java/com/ca/mas/foundation/DeviceMetadata.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MASDevice.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MASDeviceAttributeOverflowException.java
- mas-foundation/src/main/java/com/ca/mas/foundation/MASResponseBody.java
- mas-test/src/main/java/com/ca/mas/GatewayDefaultDispatcher.java
- mas-test/src/main/resources/msso_config.json
Us507853 device metadata
- TA1102462 Android Implementation 
- TA1102463 Unit Tests
> Us507853 device metadata

- mas-foundation/src/androidTest/java/com/ca/mas/foundation/MASJwtSigningTest.java
> DE393629: JWT with RS256 validation unit test case fix

- mas-foundation/src/main/java/com/ca/mas/foundation/MASUser.java
> DE394086: Logout when session lock issue

- mas-foundation/src/main/java/com/ca/mas/core/security/AndroidKeyStoreRepository.java
> Fix CSR Generation

- mas-foundation/src/main/java/com/ca/mas/core/oauth/OAuthClientUtil.java
> DE396760: Logout fails for static client

- mas-foundation/src/main/java/com/ca/mas/core/storage/sharedstorage/AccountManagerUtil.java
In the file AccountManagerUtil.java null pointer exception for accountType has been handled.
> Bugfix/DE452288 Account Manager Util

- mas-foundation/src/main/java/com/ca/mas/core/oauth/CodeVerifierCache.java
- mas-foundation/src/main/java/com/ca/mas/core/storage/sharedstorage/AccountManagerUtil.java
This is for the develop branch..
Issue:
Presently Code verifier is getting generated and stored in Memory cache. When mobile app which is built using SDK calls another external app for authentication, it goes to background. In some cases, it is getting killed by the OS. Due to this, code verifier, which is stored in memory cache is getting lost.
Fix:
SDK has a support for Shared Preference which is persistent local database for Android. Implemented the shared preference and storing the code verifier and the state. This will ensure that the values will be present although app is in background or getting killed by any chance.
We are adding a check for Null Pointer Exception for the Password and Account Name field while creating the account
> De506139 code verifier store in shared pref account mgr util change develop

- ChangeLog.md
- README.md
This branch is for MAS 2.2.00 release. We have added the versioning in our Readme and changelog files.
> Release branch for MAS 2.2.00

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- mas-connecta/build.gradle
- mas-foundation/build.gradle
- mas-storage/build.gradle
- mas/build.gradle
- masui/build.gradle
- settings.gradle
The changes we made in the build.gradle files to publish the artifacts in the maven
> Maven publish changes
